name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # main ブランチに push されたときに実行

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./publish  # ← 公開したいディレクトリを指定

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
